// Generated by CoffeeScript 1.8.0
module.exports = {
  API: require('./src/modem'),
  DemuxStream: require('./src/demuxstream'),
  HttpDuplex: require('./src/httpduplex'),
  Parameters: require('./src/parameters')
};
