// Generated by CoffeeScript 1.8.0
module.exports = (function(_this) {
  return function(stream, stdout, stderr) {
    var count, type;
    type = null;
    count = 0;
    return stream.on('readable', function() {
      var header, payload;
      while (true) {
        while (count > 0) {
          payload = stream.read(1);
          if (payload == null) {
            return;
          }
          count--;
          if (type === 2) {
            stderr.write(payload);
          } else {
            stdout.write(payload);
          }
        }
        header = stream.read(8);
        if (header == null) {
          return;
        }
        type = header.readUInt8(0);
        count = header.readUInt32BE(4);
      }
    });
  };
})(this);
